const DELETE_USER = "user:DELETE_USER"
const GET_ALL_USERS = "user:GET_ALL_USERS"
const UPDATE_USER = "user:UPDATE_USER"
const GET_USER = "user:GET_USER"
const GET_WISHLIST = "user:GET_WISHLIST"
const GET_CREDITCARDS  = "user:GET_CREDITCARDS"
const DELETE_CREDITCARD = "user:DELETE_CREDITCARD"
const ADD_CREDITCARD = "user:ADD_CREDITCARD"
const REMOVE_CREDITCARD = "user:REMOVE_CREDITCARD"
const ADD_TO_WISHLIST = "user:ADD_TO_WISHLIST"
const REMOVE_FROM_WISHLIST = "user:REMOVE_FROM_WISHLIST"
const ADD_PRODUCT = "product:ADD_PRODUCT"
const REMOVE_PRODUCT = "product:REMOVE_PRODUCT"
const GET_ALL_PRODUCTS = "product:GET_ALL_PRODUCTS"
const GET_PRODUCT = "product:GET_PRODUCT"
const UPDATE_PRODUCT = "product:UPDATE_PRODUCT"
const GET_PRODUCT_BY_CATEGORY = "product:GET_PRODUCT_BY_CATEGORY "
const GET_ALL_ORDERS = "order:GET_ALL_ORDERS"
const GET_ORDER = "order:GET_ORDER"
const DELETE_ORDER = "order:DELETE_ORDER"
const UPDATE_ORDER = "order:UPDATE_ORDER"
const CREATE_ORDER = "order:ADD_ORDER"
const ADD_CATEGORY = "category:ADD_CATEGORY"
const DELETE_CATEGORY = "category:DELETE_CATEGORY"
const GET_ALL_CATEGORIES = "category:GET_ALL_CATEGORIES"
const GET_CATEGORY = "category:GET_CATEGORY"
const UPDATE_CATEGORY = "category:UPDATE_CATEGORY"
const GET_CART = "cart:GET_CART"
const FLUSH_CART = "cart:FLUSH_CART"
const ADD_PRODUCT_TO_CART = "cart:ADD_PRODUCT_TO_CART"
const REMOVE_PRODUCT_FROM_CART = "cart:REMOVE_PRODUCT_FROM_CART"
const USE_COUPON = "cart:USE_COUPON"
const SET_ORDER_TO_DELIVERED = "order:SET_ORDER_TO_DELIVERED"
const GET_MY_ORDERS = "order:GET_MY_ORDERS"
const UPDATE_USER_BY_ID = "user:UPDATE_USER_BY_ID"
const DELETE_USER_BY_ID = "user:DELETE_USER_BY_ID"
const CREATE_COUPON = "coupon:CREATE_COUPON"
const REMOVE_COUPON = "coupon:REMOVE_COUPON"
const GET_ALL_COUPONS = "coupon:GET_ALL_COUPON"
const GET_COUPON = "coupon:GET_COUPON"
const UPDATE_COUPON = "coupon:UPDATE_COUPON"
const SET_DELIVERY_EGENT = "order:SET_DELIVERY_EGENT"
const GET_USER_BY_ID = "user:GET_USER_BY_ID"
  

module.exports = {
    GET_USER_BY_ID,
    SET_DELIVERY_EGENT,
    CREATE_COUPON,
    REMOVE_COUPON,
    GET_ALL_COUPONS,
    GET_COUPON,
    UPDATE_COUPON,
    UPDATE_USER_BY_ID,
    DELETE_USER_BY_ID,
    SET_ORDER_TO_DELIVERED,
    GET_MY_ORDERS,
    USE_COUPON,
    ADD_TO_WISHLIST,
    REMOVE_FROM_WISHLIST,
    DELETE_USER,
    GET_ALL_USERS,
    ADD_CATEGORY,
    ADD_PRODUCT,
    ADD_PRODUCT_TO_CART,
    CREATE_ORDER,
    DELETE_CATEGORY,
    DELETE_CREDITCARD,
    DELETE_ORDER,
    DELETE_USER,
    FLUSH_CART,
    GET_ALL_CATEGORIES,
    GET_ALL_ORDERS,
    GET_ALL_PRODUCTS,
    GET_ALL_USERS,
    GET_CART,
    GET_CATEGORY,
    GET_CREDITCARDS,
    GET_ORDER,
    GET_PRODUCT,
    GET_PRODUCT_BY_CATEGORY,
    GET_USER,
    GET_WISHLIST,
    REMOVE_PRODUCT,
    REMOVE_PRODUCT_FROM_CART,
    UPDATE_CATEGORY,
    UPDATE_ORDER,
    UPDATE_PRODUCT,
    UPDATE_USER,
    ADD_CREDITCARD,
    REMOVE_CREDITCARD
}